#server:
#  port: 1234
#
#  spring:
#    datasource:
#      jdbc-url: jdbc:mysql://localhost:3306/microservice_project?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
#      username: root
#      password: root
#      driver-class-name: com.mysql.jdbc.Driver
#
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#      show-sql: true
#
#
#
